
server:
  port: 8622
  servlet:
    context-path: /api/v1

spring:
  application:
    name: gd-ggfw-universa
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin123
    url: jdbc:mysql://localhost:3306/test?connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
#  data:
#    #elasticsearch
#    elasticsearch:
#      local: true  #开启 Elasticsearch 仓库(默认值:true)
#      repositories:
#        enabled: true #仓库中存储数据
#      cluster-name: elasticsearch-test  #节点名字，默认elasticsearch
#      #节点地址，多个节点用逗号隔开 #默认 9300 是 Java 客户端的端口。9200 是支持 Restful HTTP 的接口
#      cluster-nodes: http://localhost:9300
#      properties:
#        transport.tcp.connect_timeout: 120s #连接超时的时间
  elasticsearch:
    rest:
      uris: http://localhost:9200
#elasticsearch:
#  url: http://localhost:9200

#mybatis
mybatis:
  # spring boot集成mybatis的方式打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
